service: dvdstore

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-plugin-resource-tagging
  - serverless-dotenv-plugin # automatically import all variables from .env.local into functions

custom:
  prune:
    automatic: true
    includeLayers: true
    number: 10
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dotenv:
    path: ${self:service}.env.local

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage}
  region: ap-southeast-1
  stackTags:
    ProjectName: DvdStore
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    LOG_LEVEL: debug
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:DescribeParameters
        - ssm:GetParameters
        - ssm:GetParametersByPath
      Resource: "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/${self:service}/${self:provider.stage}/*"
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource:
        - "arn:aws:kms:${self:provider.region}:${aws:accountId}:key/9fa8490a-542f-4e96-b051-2b250ececa0d"

functions:
  api:
    handler: src/main/main.handler
    memorySize: 128
    description: Backend service for DVD Rental Demo App
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
